version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
  
  app:
    container_name: app
    restart: always
    build: ./nodeapp
    depends_on:
      - redis
      - mongo
      - db
    volumes: 
      - ./nodeapp:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
 
  db:
    image: postgres:9.4
    restart: always
    volumes:
      - ./pg-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

networks:
  frontend:
  backend:

